### ISSUE TITLE
Uniforming the tools used in each branch

### ISSUE THREAD

**Issue by tapyu** [khuyentran1401/data-science-template#13]
Hi there!

Besides `dvc`, `pip`, and `poetry`, I've also noticed that some tools that are used in some branches are simply not used in others. I honestly didn't see the reason for that since there isn't an alternative being used for a replacement of them...

|                          |  `hydra`  | `flake8`  |  `prefect`  | 
|          ---             | ---       |           --- |           ---      |
| `dvc-poetry`      |  ✅      |      ❌     |      ❌          |
| `dvc-pip`            | ✅      |      ❌     |      ❌          |
| `prefect-poetry` | ❌      |      ✅     |      ✅          |

- Why doesn't `prefect-poetry` use `hydra`?
- Why don't `dvc-poetry` and `dvc-pip` use `prefect` or `flake8`?

I understood the reason of having `dvc-poetry` and `dvc-pip` as `pip` and `poetry` are two different strategies to manage packages, and therefore two different templates are needed. However, `prefect-poetry` seems unnecessary as `prefect` doesn't overlap the other tools' goals.

It seems that you started with [one model](https://mathdatasimplified.com/how-to-structure-an-ml-project-for-reproducibility-and-maintainability-3/) and then you [recreated it](https://mathdatasimplified.com/how-to-structure-a-data-science-project-for-readability-and-transparency-2/), thus abandoning some tools and adopting others. I am not sure... If PR are welcoming, I propose to adopt the same set of tools, unless they are conflicting or overlapping. Let me understand what is your idea so that I can collaborate with your project :)

**Comment by khuyentran1401** [comment]
Hey Rubem, thanks for bringing this up. I'm trying to keep the template lightweight, so I only want to include the most essential tools. My priorities have shifted over time, and I now believe that DVC is more important than Prefect. If you think both tools are necessary, feel free to create a separate branch that includes both.

**Comment by tapyu** [comment]
Thank you for the feedback! Currently, I am working with other tools as well, but I am using your cookiecutter template to organize all such technologies in ready-to-use branches with a set of complementary tools. Maybe it is gonna take a while, but I will propose PRs once get acquaint with them.

**Comment by khuyentran1401** [comment]
Sounds good to me! Thanks for working on this. Let me know if you need any help.
