### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by Ronimsenn** [khuyentran1401/data-science-template#23]
Hi,
Great template, thank you for the work.

Under what licence is it licenced? My assumption is that, since no licence has been added, it is meant to be either public domain or under a very permissive licence, but it would be good to confirm by adding a licence file.

I am not sure if all of this is even licensable/copyrightable, but to be on the safe side, adding a licence would make it easier to use in commercial environments (and to explain to supervisors and the legal department that it is usable).

Best regards

**Comment by khuyentran1401** [comment]
Great suggestion! Just added an MIT license
