### ISSUE TITLE
Invalid project setup with poetry

### ISSUE THREAD

**Issue by goleng** [khuyentran1401/data-science-template#5]
Hey Khuyen, 

Thanks for creating this easy-to-use template. I really like the simple approach. 
I tried creating a template based on the instructions provided. Thus far, it works but with some issues around this line (I think): 
`python = "{{ cookiecutter.author_name }}"` in the project.toml file. 

It's referencing the author's name as opposed to the `compatible_python_versions`.

**Comment by khuyentran1401** [comment]
Thanks so much for the issue! It is fixed now
