### ISSUE TITLE
Angreal as an alternative to cookiecutter + Makefile

### ISSUE THREAD

**Issue by dylanbstorey** [khuyentran1401/data-science-template#8]
First, awesome template. I've been doing some research on what's changed on templating data science projects over the last few years and came across yours. 

Wasn't sure what the best route to reach out was so thought I'd just present it to you in an issue, I built a templating engine very similar to cookie cutter but includes the ability to include python functions as plugins for a command line interface. Thought you mind find it interesting / useful if you find maintaining / extending the Makefile annoying. 

https://angreal.github.io/angreal/

Again - awesome work !

**Comment by tapyu** [comment]
Hi! Nice Python pkg. Agreed that Makefile is annoying, but what do your pkg does that is either better than or (cannot be done with) cookiecutter + Makefile?

**Comment by dylanbstorey** [comment]
It uses python files as a plugin system for a command line interface - with a look/feel very similar to `click`.

**Comment by tapyu** [comment]
> It uses python files as a plugin system for a command line interface

I am creating another branch where I to work with AWS SageMaker with this Data Science template. I confess that CookieCutter has been doing a great job... However, I do need to write messages to the user as he/she sets the template up. I am not sure if CookieCutter does this job, though. Do your pkg can provide this level interaction with the final user during the creation of the template?

**Comment by khuyentran1401** [comment]
@tapyu Could you specify what you mean by "writing messages on the terminal to the user as he/she sets the template up"?

**Comment by tapyu** [comment]
@khuyentran1401 AWS SageMaker can be configured to work on your local machine or on the cloud. Depending on this choice, the directory structure may vary. So, I was thinking of prompting a dialog like:
```
Do you want to work on your local machine or on the cloud?
```

And with a yes/no answer. This would be used to define whether some directories should be created. AFAIK, cookiecutter can only prompt something like this:

![image](https://github.com/khuyentran1401/data-science-template/assets/22801918/7fe49821-3563-45a7-96e4-102ba055b1ee)


That wouldn't cut it...

**Comment by dylanbstorey** [comment]
The dialog renders based on the variables you want. You can also use the template specific init script for additional interaction. 

I'd recommend going through
 https://angreal.github.io/angreal/tutorials/your-first-angreal/

As a starting point. 

Alternatively if you want to open an issue on the angreal repo I can support you without polluting this projects issues page.

**Comment by dylanbstorey** [comment]
The dialog renders based on the variables you want. You can also use the template specific init script for additional interaction. 

I'd recommend going through
 https://angreal.github.io/angreal/tutorials/your-first-angreal/

As a starting point. 

Alternatively if you want to open an issue on the angreal repo I can support you without polluting this projects issues page.

**Comment by tapyu** [comment]
> You can also use the template specific init script for additional interaction.

`init.py` runs after the variables are set, not before them...

```
❯ angreal init meeting_notes
name? ["another_meeting"]: 
cadence? ["weekly"]: 
standing_agenda? ["Complaints"]: 
Hi from init.py another_meeting !
Angreal template (meeting_notes) successfully rendered !
```

**Comment by dylanbstorey** [comment]
1. You can use the default values to all the question, but I'd suggest defaults and documentation is a better pattern.  

If you'd like to change that interface,  pull requests are welcome.  

2. Yes init runs after rendering with the first set of variables.  But you can gather additional inputs during the init script an conditionally render during that phase.

**Comment by khuyentran1401** [comment]
Hi @dylanbstorey, thanks for the issue. For now, the cookiecutter + Makefile pattern works so I will keep it for now. Thanks for the suggestions.
